### ISSUE TITLE
Sort reminders by due date/time

### ISSUE THREAD

**Issue by brycekwon** [streetwriters/notesnook#3594] opened 2023-10-19 10:03 UTC
### What problem are you facing?

Currently, the only sorting methods for reminders in relation to time are `Date edited` and `Date created`. This causes some disorganization when scheduling reminders out of order, making it hard to keep track of them as the list builds up.

### What's the solution you'd like to see in Notesnook?

It would be nice to be able to sort reminders by their due dates/times.

**Comment by thecodrr** [comment] 2023-10-30 09:30
Duplicate of #2366

**Closed by thecodrr** 2023-10-30 09:30 UTC
Labels: Type: Feature Request, Status: Pending
