### ISSUE TITLE
Note properties sheet collapses on action [Android]

### ISSUE THREAD

**Issue by luxcalor** [streetwriters/notesnook#2424] opened 2023-04-25 23:22 UTC
### What happened?

Note properties sheet collapses on every button tap, doesn't seem to be intended, especially in the case of managing notebooks linking.

https://user-images.githubusercontent.com/76074147/234428096-72654fe3-6d43-4148-a769-40f09e9ad3da.mp4

### Steps to reproduce the problem

See video above. 

### Version

2.4.13

### Platform/OS

Android

**Comment by ammarahm-ed** [comment] 2023-04-26 03:32
I think this is the intended behavior. Usually when a user opens the properties, it's for one-off action. In case of Notebook linking/history etc the sheet just navigates to the next sheet without closing. Pin/Favorite/Read only/Local only etc are toggles and cause the sheet to close once you have taken the action.

**Comment by luxcalor** [comment] 2023-04-26 09:20
> In case of Notebook linking/history etc the sheet just navigates to the next sheet without closing. 

When linking yes, it goes to the next sheet. But when editing existing notebook linkage it is rather confusing. You tap on a notebook or a topic in top of properties, the properties sheet immidiately closes. Then you have to open the properties again to realize there is now another button to remove the note from the notebook/topic. Wouldn't call it seamless or intuitive.

> Pin/Favorite/Read only/Local only etc are toggles and cause the sheet to close once you have taken the action.

Would be more user friendly to let a user decide when to close the sheet, I think. A lot of times several actions are intended to be performed at the same time: for example pining and adding to favorites, making it read only and pinning to notification, etc. I would definitely prefer the sheet to not close until I checked all I need.

**Comment by ammarahm-ed** [comment] 2023-04-26 10:30
@luxcalor I see now, yes. Actually that is a bug because a single tap on the topic should navigate to the topic (which it does) but does not close the editor. Currently long-press a topic at top of properties results in note getting removed from that topic.

On your second point, i will have to rethink this.

**Comment by thecodrr** [comment] 2023-09-14 11:21
The bug in this issue has been fixed. The app now navigates to the topic or notebook when clicking on it in the Notes properties.

As for multiple actions without the sheet closing; I don't think that's how modals or sheets work. You take an action and move on. Just like a context menu.

**Closed by thecodrr** 2023-09-14 11:21 UTC
Labels: Type: Bug, Status: Pending
