### ISSUE TITLE
Cannot play audio/video files (note attachment) inside notesnook app

### ISSUE THREAD

**Issue by gaganyadav80** [streetwriters/notesnook#390] opened 2022-03-09 07:52 UTC
**Is your feature request related to a problem? Please describe.**
Audio/Video files or any file other than images attached inside notes cannot be played right inside the app on both mobile and desktop.

**Describe the solution you'd like**
Allow playing audio/video files right inside the app. Also if some other type of file is attached (other than images) ie. pdf then also allow to view it inside the app (mobile/desktop).

**Describe alternatives you've considered**
Download each document and then view it separately.

**Additional context**
NA

**Comment by thecodrr** [comment] 2022-03-09 09:15
Duplicate of #179

**Closed by thecodrr** 2022-03-09 09:15 UTC
