### ISSUE TITLE
URGENT WARNING: NOTESNOOK WILL LOSE YOUR NOTES

### ISSUE THREAD

**Issue by busykittenfk** [streetwriters/notesnook#5347] opened 2024-05-04 22:35 UTC
### What happened?

Many times I've created or edited a note on my iphone and closed the app thinking it was saved. A few minutes later, I open the app, and the note/edit is no where to be found. The note history has no record of it ever being created/edited. Also checked on my computer and the note was never sync'd there. The app worked perfectly before, but this new v3 has destroyed a once great app. I will be switching and telling everyone in the privacy community to switch if this is not addressed immediately.

### Steps to reproduce the problem

1. Create new note on iPhone (or edit existing note)
2. Force close app
3. Reopen app

Note: background app refresh is off.

### Version

3.0.1 on iOS

### Platform/OS

iOS

**Comment by busykittenfk** [comment] 2024-05-05 00:10
After more testing, it seems like the note never gets saved in the first place. For example, if I edit a note, the last saved time doesn't update. I've still got the app open and it says the note was edited 2h ago, despite me just editing it and seeing the edits I made. There's no way to force the app to save the edits. Once I close the app, the edits are gone and the note is reverted back to 2h ago. Just horrible that you've ruined such a great app. Did you guys ever think about beta testing??

**Comment by fazsune** [comment] 2024-05-05 03:49
I reported a similar issue (on android) on #5345 as I noticed that my notes would stop saving at all. I was able to get around this by copying whatever I wrote down to my clipboard, restarting the app, and then attempting to update the note again (usually worked). It gave me anxiety when I first noticed it, and this has been an issue since the v3 beta (back when I updated before stable released).

**Comment by ammarahm-ed** [comment] 2024-05-17 09:06
Hey @fazsune can you update to the latest version on android, v3.0.7 and check if you are still facing this issue?

**Comment by fazsune** [comment] 2024-05-17 15:10
> Hey @fazsune can you update to the latest version on android, v3.0.7 and check if you are still facing this issue? When do you usually see this issue?

I've been keeping my app up-to-date for a while now and I don't think I've came across the issue following v3.0.3 / v3.0.4; however, it was an infrequent bug so in case I do come across it again I'll let you know.

> 1. Do you see the issue when you keep the app in background for a long time and return to make some changes?

Yes, and this was what I initially deduced was the cause of the issue since it only happened whenever I left the app running in the background.

 > 2. Does the rest of the app work when you notice that changes are not saving, like pressing the back button in editor or switching the tabs etc, do those actions work or they stop responding too?

Everything else works fine, it's only the notes that stop saving.

**Comment by thecodrr** [comment] 2024-07-01 06:41
This was happening due to clearing logs taking too long and it was fixed in v3.0.7.

**Closed by thecodrr** 2024-07-01 06:41 UTC
Labels: Type: Bug, Status: Pending
