### ISSUE TITLE
creation date edit

### ISSUE THREAD

**Issue by c4r1u** [streetwriters/notesnook#2333] opened 2023-04-12 16:01 UTC
### What problem are you facing?

![Screenshot_20230412_185044_Notesnook](https://user-images.githubusercontent.com/130585526/231515234-b1bd51e1-eb2d-419d-987d-452b880278e0.jpg)

### What's the solution you'd like to see in Notesnook?

The ability to edit the "created at" date and input a custom date. the same way you can edit a title

**Comment by thecodrr** [comment] 2023-04-15 00:29
Duplicate of #401

**Closed by thecodrr** 2023-04-15 00:29 UTC
Labels: Type: Feature Request, Status: Pending
