### ISSUE TITLE
Linux desktop app: problems typing a note title 

### ISSUE THREAD

**Issue by avatar382** [streetwriters/notesnook#553] opened 2022-05-05 21:10 UTC
**Describe the bug**
When typing a note title, the outcome of what appears on the screen is strangely delayed and garbled

**To Reproduce**
1. Click on new note button
2. Focus mouse on title area
3. Type the phrase "testing testing 123" on keyboard at a moderate typing speed
4. As phrase is typed, it does not appear continuously, but it looks like it's glitching out. Letters appear and disappear. The final string that appears in the title box is "test3"

Note: when the phrase is typed very slowly, this problem does not occur.

At the moment I have resorted to typing my titles in another app and then copy-pasting them into notesnook.

**Expected behavior**
The exact string typed by the user is expected in the title box, regardless of the speed of typing

**Screenshots**

**Desktop (please complete the following information):**
Ubuntu Linux 21.10, 5.13.0-40-generic
App version is 1.8.8-ec26a54-desktop

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thecodrr** [comment] 2022-05-07 06:37
I have tried this on the Web & Desktop app but cannot reproduce this no matter how fast I type.

**Comment by avatar382** [comment] 2022-05-11 20:00
Hmm, that's strange.

My Linux system is running the XFCE window manager (4.16), I wonder if it's related to that or to GTK. What distro/WM did you test with?

**Comment by jordanhandy** [comment] 2022-05-12 01:04
I can reproduce this on Windows. If I create a note, write in it, then quickly create another note, the note title is delayed in typing and characters appear out of order.

It's almost as if a sync and write operation are competing as a brand new note was just created while also attempting to be synced up.

**Comment by thecodrr** [comment] 2022-05-12 07:40
I am looking into this. Is this happening in v1.8.9?

**Comment by thecodrr** [comment] 2022-05-12 07:47
> My Linux system is running the XFCE window manager (4.16), I wonder if it's related to that or to GTK. What distro/WM did you test with?

@avatar382 I am on Kubuntu 22.04 with KDE. I doubt that makes a difference though. I'll keep trying to repro this.

**Comment by jordanhandy** [comment] 2022-05-12 11:47
> I am looking into this. Is this happening in v1.8.9?

Yes

**Comment by jordanhandy** [comment] 2022-05-12 22:22
@thecodrr 
In case it helps you, I recorded a small video to showcase the issue.  This is on the 1.8.9 using macOS.  You'll see I'm typing at what I consider "normal" speed, and the cursor jumps around all wonky.  When I deliberately slow down, I can finish my words.

Hope it helps.

[Video Here](https://res.cloudinary.com/dakfccuv5/video/upload/v1652393893/Issue_Video_Example_hq69ju.mp4)

**Comment by thecodrr** [comment] 2022-05-13 12:48
>  I recorded a small video to showcase the issue. 

Wow. That's an annoying issue. I'll fix this ASAP.

**Comment by thecodrr** [comment] 2022-06-06 09:57
Fixed. Will be released in the next version.

**Closed by thecodrr** 2022-06-06 09:57 UTC
