### ISSUE TITLE
Partner Sharing (Collaborative)

### ISSUE THREAD

**Issue by libbyslayer** [streetwriters/notesnook#6690] opened 2024-10-12 14:04 UTC
### What problem are you facing?

Option to set someone as Partner and share selected or all notes with them.

### What's the solution you'd like to see in Notesnook?

Have real time collaboration features or restrict collaborations and view only option.

### What alternatives have you considered?

*No response*

### Additional context

*No response*

<sub><a href="https://huly.app/guest/streetwriters?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBhODFlNWM3ZDZhNTZhOGY5NTIwZTAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJkdWxsYWhhdHRhLXN0cmVldHdyaXRlci02NzA4YjYxMi0wMDA4OTgyNWM5LTRkY2EzOCJ9.8SMRXBtR_ava-YAVPzPLXKV52K_Wod5BUPFISRyETns">Huly&reg;: <b>NN-6556</b></a></sub>

**Comment by thecodrr** [comment] 2024-10-12 18:33
Duplicate of #20

**Closed by thecodrr** 2024-10-12 18:33 UTC
Labels: Type: Feature Request, Status: Pending
