### ISSUE TITLE
Sync bug.

### ISSUE THREAD

**Issue by caiuaqui** [streetwriters/notesnook#3839] opened 2023-11-20 22:23 UTC
### What happened?

HI,

Anytime I manually press the sync icon on the bottom bar, the app turns into a blank screen without letting me do anything.
I, then, have to close the app and open again.

Here's an example: 
![imagem](https://github.com/streetwriters/notesnook/assets/6917622/8c5df2a6-8207-4f8f-a533-f1245e05da90)

Device information:
App version: 2.610-a101dbd-desktop
OS: Windows 10 64-bit
Browser: Electron 25.9.3
Pro: false

### Steps to reproduce the problem

Open the app.
Manually press the sync icon on the bottom bar.
App turns into a blank screen.

### Version

2.6.10-a101dbd-desktop

### Platform/OS

Windows

### Relevant log output

```shell
{"level":3,"message":"Getting route for path: /","timestamp":1700517674214,"scope":"notesnook-web","elapsed":14}
{"level":3,"message":"Database initialization took 155.30ms","timestamp":1700517674370,"scope":"notesnook-web","elapsed":156}
{"level":3,"message":"app render took 34.70ms","timestamp":1700517674427,"scope":"notesnook-web","elapsed":57}
{"level":3,"message":"Saving new token","timestamp":1700517732770,"extras":{"access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjFENzU4RjgzQkI5RkVENjJEODg0OTdBNkQ4QzQ5OEJERDk3OTkxQjg0M0RBNjY3NEEwNjQ1MUQ1MjVFQTA0MkIiLCJ0eXAiOiJhdCtqd3QiLCJjdHkiOiJKV1QifQ.eyJuYmYiOjE3MDA1MTc3MjEsImV4cCI6MTcwMDUxODkyMSwiaXNzIjoiaHR0cDovLzEwLjAuMC45IiwiY2xpZW50X2lkIjoibm90ZXNub29rIiwic3ViIjoiNjQ0MDM4NzhhNzc2ZTRkNzhlYzFiZDllIiwiYXV0aF90aW1lIjoxNzAwNTE3NzIxLCJpZHAiOiJsb2NhbCIsInJvbGUiOiJub3Rlc25vb2siLCJub3Rlc25vb2s6c3RhdHVzIjoiYmFzaWMiLCJtZmE6cHJpbWFyeSI6ImFwcCIsIm5vdGVzbm9vazptYXJrZXRpbmdfY29uc2VudCI6ImZhbHNlIiwianRpIjoiNjZGRDc2QTZBRkZFNTkyMTgyRUFDQjhENThDNUM1NTQiLCJpYXQiOjE3MDA1MTc3MjEsInNjb3BlIjpbImF1dGg6Z3JhbnRfdHlwZXM6bWZhIl19.bf9VhhlADNOkUADoZl9zrLOfFM46PtuJj5Fo4QycWrZb2Rb59UUTK15Gb1h42tQ2loNmVtNOC9FPdwmNJnKfLNAViHuVc8gWeBd3ZQNYBV60VN6G20EbN1ARgOURT0w94ThftgkwbI5W6_kycFpXt4tWkxauMpqTJSsAcLag-mm4vbK0Ie66L7dWH-iH39YdKuNZIq9D9HWOOOg5LQwBYLqaXKFYhgkWPNfmwblLro2PqltXXgWS1vfWYSx38678K5vyDALYnJZp8GsKAShEpOzyYaUY2_YExi7VpRNUHDtJ4sazSva1lquvmWiNw09C0Mv4lrPtSz2pXuJay1UngQ","expires_in":1200,"token_type":"Bearer","scope":"auth:grant_types:mfa","additional_data":{"primaryMethod":"app"}},"scope":"TokenManager","elapsed":58570}
{"level":3,"message":"Getting route for path: /","timestamp":1700517742954,"scope":"notesnook-web","elapsed":1}
{"level":3,"message":"Database initialization took 40.20ms","timestamp":1700517742994,"scope":"notesnook-web","elapsed":40}
{"level":3,"message":"app render took 103.20ms","timestamp":1700517743146,"scope":"notesnook-web","elapsed":152}
{"level":3,"message":"Access token requested","timestamp":1700517743584,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":590}
{"level":3,"message":"Access token requested","timestamp":1700517743894,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":310}
{"level":3,"message":"Sync status updated: syncing","timestamp":1700517744039,"scope":"notesnook-web","elapsed":893}
{"level":3,"message":"Auto sync requested","timestamp":1700517744048,"scope":"AutoSync","elapsed":1095}
{"level":3,"message":"Auto sync started","timestamp":1700517744049,"scope":"AutoSync","elapsed":1}
{"level":3,"message":"Starting sync","timestamp":1700517744063,"extras":{"full":true,"force":false,"serverLastSynced":null},"scope":"Sync","elapsed":1110}
{"level":3,"message":"Access token requested","timestamp":1700517744064,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":1111}
{"level":3,"message":"Initialized sync","timestamp":1700517744437,"extras":{"lastSynced":0,"oldLastSynced":0},"scope":"Sync","elapsed":374}
{"level":3,"message":"Data fetched","timestamp":1700517750345,"extras":{"lastSynced":1700516632116},"scope":"Sync","elapsed":5908}
{"level":3,"message":"Uploading attachments...","timestamp":1700517750346,"extras":{"total":0},"scope":"Sync","elapsed":1}
{"level":3,"message":"Access token requested","timestamp":1700517750347,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":7394}
{"level":3,"message":"No new data to send.","timestamp":1700517750372,"scope":"Sync","elapsed":26}
{"level":3,"message":"Access token requested","timestamp":1700517750373,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":6479}
{"level":3,"message":"Stopping sync","timestamp":1700517750506,"extras":{"lastSynced":1700516632116},"scope":"Sync","elapsed":134}
{"level":3,"message":"Sync status updated: completed","timestamp":1700517750510,"scope":"notesnook-web","elapsed":6471}
{"level":3,"message":"Sync status updated: completed","timestamp":1700517750514,"scope":"notesnook-web","elapsed":4}
{"level":3,"message":"refreshing app took 45.70ms","timestamp":1700517750562,"scope":"notesnook-web","elapsed":48}
{"level":3,"message":"Sync status updated: synced","timestamp":1700517753998,"scope":"notesnook-web","elapsed":3436}
{"level":3,"message":"Access token requested","timestamp":1700517763654,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":13307}
{"level":3,"message":"Sync requested by: settings","timestamp":1700517775381,"scope":"AutoSync","elapsed":31332}
{"level":3,"message":"Sync status updated: syncing","timestamp":1700517775499,"scope":"notesnook-web","elapsed":21501}
{"level":3,"message":"Auto sync requested","timestamp":1700517775501,"scope":"AutoSync","elapsed":120}
{"level":3,"message":"Starting sync","timestamp":1700517775502,"extras":{"full":false,"force":false,"serverLastSynced":null},"scope":"Sync","elapsed":24996}
{"level":3,"message":"Uploading attachments...","timestamp":1700517775520,"extras":{"total":0},"scope":"Sync","elapsed":0}
{"level":3,"message":"Access token requested","timestamp":1700517775524,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":11870}
{"level":3,"message":"Batch sent (1)","timestamp":1700517775844,"scope":"Sync","elapsed":324}
{"level":3,"message":"New data sent","timestamp":1700517776043,"scope":"Sync","elapsed":199}
{"level":3,"message":"Access token requested","timestamp":1700517776051,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":25678}
{"level":3,"message":"Stopping sync","timestamp":1700517776167,"extras":{"lastSynced":1700517775520},"scope":"Sync","elapsed":124}
{"level":3,"message":"Sync status updated: completed","timestamp":1700517776174,"scope":"notesnook-web","elapsed":675}
{"level":3,"message":"Sync status updated: completed","timestamp":1700517776193,"scope":"notesnook-web","elapsed":19}
{"level":3,"message":"refreshing app took 98.40ms","timestamp":1700517776293,"scope":"notesnook-web","elapsed":100}
{"level":3,"message":"Sync status updated: synced","timestamp":1700517779180,"scope":"notesnook-web","elapsed":2887}
{"level":3,"message":"Sync status updated: syncing","timestamp":1700517797482,"scope":"notesnook-web","elapsed":18302}
{"level":3,"message":"Auto sync requested","timestamp":1700517797484,"scope":"AutoSync","elapsed":21983}
{"level":3,"message":"Starting sync","timestamp":1700517797494,"extras":{"full":true,"force":false,"serverLastSynced":null},"scope":"Sync","elapsed":21327}
{"level":3,"message":"Initialized sync","timestamp":1700517797504,"extras":{"lastSynced":1700517775520,"oldLastSynced":1700517775520},"scope":"Sync","elapsed":10}
{"level":3,"message":"Uploading attachments...","timestamp":1700517797641,"extras":{"total":0},"scope":"Sync","elapsed":0}
{"level":3,"message":"Access token requested","timestamp":1700517797649,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":22125}
{"level":3,"message":"No new data to send.","timestamp":1700517797693,"scope":"Sync","elapsed":52}
{"level":3,"message":"Access token requested","timestamp":1700517797706,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":21655}
{"level":3,"message":"Stopping sync","timestamp":1700517797848,"extras":{"lastSynced":1700517775520},"scope":"Sync","elapsed":155}
{"level":3,"message":"Sync status updated: failed","timestamp":1700517797850,"scope":"notesnook-web","elapsed":368}
{"level":1,"message":"Error: Connection closed.\n    at HubConnection.<anonymous> (https://app.notesnook.com/assets/index-3404a24b.js:380:130499)\n    at https://app.notesnook.com/assets/index-3404a24b.js:380:49642\n    at Array.forEach (<anonymous>)\n    at HubConnection._completeClose (https://app.notesnook.com/assets/index-3404a24b.js:380:49627)\n    at HubConnection._connectionClosed (https://app.notesnook.com/assets/index-3404a24b.js:380:49188)\n    at HubConnection.connection.onclose (https://app.notesnook.com/assets/index-3404a24b.js:380:39022)\n    at HttpConnection._stopConnection (https://app.notesnook.com/assets/index-3404a24b.js:380:76677)\n    at transport.onclose (https://app.notesnook.com/assets/index-3404a24b.js:380:73911)\n    at WebSocketTransport._close (https://app.notesnook.com/assets/index-3404a24b.js:380:65259)\n    at WebSocketTransport.stop (https://app.notesnook.com/assets/index-3404a24b.js:380:64756)","timestamp":1700517797852,"scope":"Sync","elapsed":4}
{"level":3,"message":"Sync status updated: completed","timestamp":1700517797853,"scope":"notesnook-web","elapsed":3}
{"level":3,"message":"Sync status updated: completed","timestamp":1700517797871,"scope":"notesnook-web","elapsed":18}
{"level":3,"message":"refreshing app took 29.30ms","timestamp":1700517797901,"scope":"notesnook-web","elapsed":30}
{"level":3,"message":"Sync status updated: synced","timestamp":1700517800861,"scope":"notesnook-web","elapsed":2960}
{"level":3,"message":"Sync requested by: 647a5cc75959599d3845454a","timestamp":1700517804721,"scope":"AutoSync","elapsed":7237}
{"level":3,"message":"Sync requested by: 647a5cc75959599d38454549","timestamp":1700517805743,"scope":"AutoSync","elapsed":1022}
{"level":3,"message":"Sync requested by: 647a5cc75959599d38454549","timestamp":1700517809686,"scope":"AutoSync","elapsed":3943}
{"level":3,"message":"Sync requested by: 647a5cc75959599d38454549","timestamp":1700517813870,"scope":"AutoSync","elapsed":4184}
{"level":3,"message":"Sync requested by: 647a5cc75959599d38454549","timestamp":1700517817960,"scope":"AutoSync","elapsed":4090}
{"level":3,"message":"Access token requested","timestamp":1700517823825,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":26176}
{"level":3,"message":"Access token requested","timestamp":1700517824469,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":644}
{"level":3,"message":"Access token requested","timestamp":1700517827206,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":2737}
{"level":3,"message":"Page visibility changed. Reconnecting SSE...","timestamp":1700517845659,"scope":"notesnook-web","elapsed":44798}
{"level":3,"message":"Page visibility changed. Reconnecting SSE...","timestamp":1700517869732,"scope":"notesnook-web","elapsed":24073}
{"level":3,"message":"Page visibility changed. Reconnecting SSE...","timestamp":1700517889329,"scope":"notesnook-web","elapsed":19597}
{"level":3,"message":"Getting route for path: /","timestamp":1700517950838,"scope":"notesnook-web","elapsed":12}
{"level":3,"message":"Access token requested","timestamp":1700517950912,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":86}
{"level":3,"message":"Database initialization took 74.50ms","timestamp":1700517950913,"scope":"notesnook-web","elapsed":75}
{"level":3,"message":"app render took 128.50ms","timestamp":1700517951092,"scope":"notesnook-web","elapsed":179}
{"level":3,"message":"Access token requested","timestamp":1700517951789,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":877}
{"level":3,"message":"Access token requested","timestamp":1700517952052,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":263}
{"level":3,"message":"Access token requested","timestamp":1700517954902,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":4076}
{"level":3,"message":"Access token requested","timestamp":1700517966230,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":11328}
{"level":3,"message":"Access token requested","timestamp":1700517968582,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":2352}
{"level":3,"message":"Access token requested","timestamp":1700517987075,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":18493}
{"level":3,"message":"Page visibility changed. Reconnecting SSE...","timestamp":1700517987450,"scope":"notesnook-web","elapsed":36358}
{"level":3,"message":"Access token requested","timestamp":1700517987741,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":666}
{"level":3,"message":"Access token requested","timestamp":1700517989964,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":2223}
{"level":3,"message":"Access token requested","timestamp":1700518000547,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":10583}
{"level":3,"message":"Access token requested","timestamp":1700518002691,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":2144}
{"level":3,"message":"Access token requested","timestamp":1700518004095,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":1404}
{"level":3,"message":"Access token requested","timestamp":1700518009741,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":5646}
{"level":3,"message":"Getting route for path: /","timestamp":1700518090663,"scope":"notesnook-web","elapsed":13}
{"level":3,"message":"Database initialization took 119.20ms","timestamp":1700518090782,"scope":"notesnook-web","elapsed":119}
{"level":3,"message":"app render took 119.70ms","timestamp":1700518090926,"scope":"notesnook-web","elapsed":144}
{"level":3,"message":"Access token requested","timestamp":1700518091487,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":705}
{"level":3,"message":"Access token requested","timestamp":1700518091745,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":258}
{"level":3,"message":"Access token requested","timestamp":1700518094930,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":4280}
{"level":3,"message":"Getting route for path: /","timestamp":1700518339641,"scope":"notesnook-web","elapsed":13}
{"level":3,"message":"Access token requested","timestamp":1700518339775,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":147}
{"level":3,"message":"Database initialization took 134.50ms","timestamp":1700518339776,"scope":"notesnook-web","elapsed":135}
{"level":3,"message":"app render took 117.30ms","timestamp":1700518339917,"scope":"notesnook-web","elapsed":141}
{"level":3,"message":"Access token requested","timestamp":1700518340513,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":738}
{"level":3,"message":"Access token requested","timestamp":1700518340763,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":250}
{"level":3,"message":"Page visibility changed. Reconnecting SSE...","timestamp":1700518362533,"scope":"notesnook-web","elapsed":22616}
{"level":3,"message":"Page visibility changed. Reconnecting SSE...","timestamp":1700518403710,"scope":"notesnook-web","elapsed":41177}
{"level":3,"message":"Sync status updated: syncing","timestamp":1700518408708,"scope":"notesnook-web","elapsed":4998}
{"level":3,"message":"Auto sync started","timestamp":1700518408712,"scope":"AutoSync","elapsed":0}
{"level":3,"message":"Starting sync","timestamp":1700518408717,"extras":{"full":true,"force":false,"serverLastSynced":null},"scope":"Sync","elapsed":69089}
{"level":3,"message":"Access token requested","timestamp":1700518408720,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":69092}
{"level":3,"message":"Initialized sync","timestamp":1700518409137,"extras":{"lastSynced":1700517775520,"oldLastSynced":1700517775520},"scope":"Sync","elapsed":420}
{"level":3,"message":"Data fetched","timestamp":1700518409346,"extras":{"lastSynced":1700517775520},"scope":"Sync","elapsed":209}
{"level":3,"message":"Uploading attachments...","timestamp":1700518409347,"extras":{"total":0},"scope":"Sync","elapsed":1}
{"level":3,"message":"Access token requested","timestamp":1700518409350,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":69722}
{"level":3,"message":"Getting route for path: /","timestamp":1700518418637,"scope":"notesnook-web","elapsed":10}
{"level":3,"message":"Database initialization took 115.40ms","timestamp":1700518418753,"scope":"notesnook-web","elapsed":116}
{"level":3,"message":"app render took 117.80ms","timestamp":1700518418889,"scope":"notesnook-web","elapsed":136}
{"level":3,"message":"Access token requested","timestamp":1700518419412,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":659}
{"level":3,"message":"Access token requested","timestamp":1700518419696,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":284}
{"level":3,"message":"Page visibility changed. Reconnecting SSE...","timestamp":1700518427490,"scope":"notesnook-web","elapsed":8601}
{"level":3,"message":"Page visibility changed. Reconnecting SSE...","timestamp":1700518463090,"scope":"notesnook-web","elapsed":35600}
{"level":3,"message":"Page visibility changed. Reconnecting SSE...","timestamp":1700518527726,"scope":"notesnook-web","elapsed":64636}
{"level":3,"message":"Getting route for path: /","timestamp":1700518804110,"scope":"notesnook-web","elapsed":15}
{"level":3,"message":"Database initialization took 127.50ms","timestamp":1700518804237,"scope":"notesnook-web","elapsed":127}
{"level":3,"message":"app render took 119.00ms","timestamp":1700518804376,"scope":"notesnook-web","elapsed":139}
{"level":3,"message":"Access token requested","timestamp":1700518805037,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":800}
{"level":3,"message":"Access token requested","timestamp":1700518805353,"extras":{"accessToken":"DB2BA8BB37"},"scope":"TokenManager","elapsed":316}
{"level":3,"message":"Page visibility changed. Reconnecting SSE...","timestamp":1700518836326,"scope":"notesnook-web","elapsed":31950}
{"level":3,"message":"Page visibility changed. Reconnecting SSE...","timestamp":1700518867460,"scope":"notesnook-web","elapsed":31134}
{"level":3,"message":"Page visibility changed. Reconnecting SSE...","timestamp":1700518870313,"scope":"notesnook-web","elapsed":2853}
{"level":3,"message":"Page visibility changed. Reconnecting SSE...","timestamp":1700518875246,"scope":"notesnook-web","elapsed":4933}
{"level":3,"message":"Page visibility changed. Reconnecting SSE...","timestamp":1700518878238,"scope":"notesnook-web","elapsed":2992}
{"level":3,"message":"Page visibility changed. Reconnecting SSE...","timestamp":1700518911910,"scope":"notesnook-web","elapsed":33672}
```

**Comment by thecodrr** [comment] 2023-11-21 03:09
@caiuaqui I cannot reproduce this on Windows 11, v2.6.10

**Comment by caiuaqui** [comment] 2023-11-21 12:23
I tried reinstalling the app, but now I have another weird behavior. 

This time, after a few seconds the app is open, I'm presented with the same blank screen.
I reinstalled yet again and the same thing happens.

The only way I found to circumvent this, was to acess using the web app and alter any note.
Then, I open the desktop app and I'm greeted with the warning about merge conflicts.
I accept the newer version and after some seconds, the app just show the same blank screen.

**Comment by caiuaqui** [comment] 2023-11-21 13:03
I'll send it later today.

**Comment by caiuaqui** [comment] 2023-11-21 21:52
Update:

Using Ctrl + Shift + I does not work on the blank page, it does nothing.

However for a brief period (before turning to the blank screen again due to the notesnook pro promotion pop-up) I was able to open the dev tools and unlocked it to a separate window.

And, after this the blank screen appeared once again ( I have to remind you that this was in a really brief period of time).


![imagem](https://github.com/streetwriters/notesnook/assets/6917622/0fb09994-2e46-49df-ac72-e6aca72c5365)

**Comment by thecodrr** [comment] 2023-11-22 03:54
@caiuaqui the last resort is clearing the app data directories. Notesnook's data directory is located at `%APPDATA%\Notesnook`. You can either delete it or move it to a different location. Do note that deleting/moving this directory will log you out.

**Comment by caiuaqui** [comment] 2023-11-22 21:11
Well, unfornately it didn't work.

I deleted the `%APPDATA%\Notesnook`  folder and proceded to login again. No issues here, all my notes were synced.

I then proceded to edit a note, more specifically, a table inside a note and before I knew it blank screen again.

**Comment by thecodrr** [comment] 2023-11-23 03:33
@caiuaqui this very issue appeared on Linux before but I haven't seen any reports of it on Windows. I think it has something to do with Electron. Would you be willing to test a version with a different Electron version?

**Comment by caiuaqui** [comment] 2023-11-23 09:21
Sure. 

Just one question, will I have to compile myself that version?

**Comment by thecodrr** [comment] 2023-11-24 04:52
@caiuaqui no, of course not. I'll send you a link and you can download it.

**Closed** 2024-04-18 08:21 UTC
Labels: Type: Bug, Platform: Desktop, Status: Can't reproduce
