### ISSUE TITLE
Ability to use passkeys for 2FA

### ISSUE THREAD

**Issue by Caotenhoch2** [streetwriters/notesnook#3740] opened 2023-11-09 12:45 UTC
### What problem are you facing?

Even though Authenticator Apps and SMS Authentication are already supported, there isn't the possibility to use passkeys as a 2FA Methode

### What's the solution you'd like to see in Notesnook?

Implement passkeys as a 2FA methode

**Comment by thecodrr** [comment] 2023-11-10 04:55
Duplicate of #428

**Closed by thecodrr** 2023-11-10 04:55 UTC
Labels: Type: Feature Request, Status: Pending
