### ISSUE TITLE
Table adjustments

### ISSUE THREAD

**Issue by MsJonesy** [streetwriters/notesnook#407] opened 2022-03-16 20:49 UTC
Am I missing something when trying to adjust a table? 

If I adjust one column, it spaces the other to compensate for the original size. Playing with them px doesn’t seem to help much.

I really could do without a gigantic table when it’s only two or three columns.

**Comment by MsJonesy** [comment] 2022-03-30 23:02
Is there any response to this?

**Comment by thecodrr** [comment] 2022-04-01 17:05
Hi, there's currently no way to insert variable width tables. This will be possible in the new editor coming in April.

**Comment by MsJonesy** [comment] 2022-04-01 18:54
Okay, this sounds interesting.Thank you for getting back to me with an update.

**Comment by thecodrr** [comment] 2022-07-18 02:18
The new editor has been released. Marking this as resolved. Feel free to reopen if the issue is still there.

**Closed by thecodrr** 2022-07-18 02:18 UTC
