### ISSUE TITLE
Comment/Pop up for words or a sentence. 

### ISSUE THREAD

**Issue by Starship-Headlight** [streetwriters/notesnook#3697] opened 2023-11-02 13:13 UTC
### What problem are you facing?

Is it possible to add an option to add comments in a word/sentence that will pop up when you hover your cursor over the word or sentence, Something like embedded links or Wikipedia. It will help add more information for specific sections in a note.

Please take a look into this. Thanks🙂

**Comment by thecodrr** [comment] 2023-11-06 04:03
Duplicate of #2612

**Closed by thecodrr** 2023-11-06 04:03 UTC
Labels: Type: Feature Request, Status: Pending
