### ISSUE TITLE
Yet another sync error + Feature request

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#461] opened 2022-03-30 03:04 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/51019003/160742684-bbf3948f-5195-491f-b77b-4d5d107fbcb8.png)

**Smartphone:**
 - Device: Samsung Galaxy S10+
 - OS: Android 12
 - Version: 1.8.4

**Feature Request**

Create a menu within all the apps that show every previous error message, and allow you to automatically report them to GitHub with the logs attached. As of right now, if you see an error, you have like 2 seconds to react

**Comment by thecodrr** [comment] 2022-04-01 15:18
Looks like a duplicate of #158

**Closed by thecodrr** 2022-04-01 15:18 UTC
