### ISSUE TITLE
collaborative resource for translation into other languages

### ISSUE THREAD

**Issue by fallsdevil** [streetwriters/notesnook#3493] opened 2023-09-30 18:08 UTC
I'd like to suggest a page/website so that users could help translate notesnook into their languages, something that happens among other apps.

Taking advantage of this post, I would also like to suggest, in the app's themes tab, the possibility of the theme creator's name being clicklabe so that we can support them in some way, for example by following them on social medias, and things like that.

**Comment by thecodrr** [comment] 2023-10-28 07:55
Closing as duplicate of #951

**Closed by thecodrr** 2023-10-28 07:55 UTC
