### ISSUE TITLE
Importer: Onenote: Failed to get sectionGroup

### ISSUE THREAD

**Issue by brashesvoucher** [streetwriters/notesnook#876] opened 2022-09-04 12:36 UTC
Hi team, getting 404 errors when trying to import from OneNote. I have around 100 pages, but the importer tool is finding only 3.

![image](https://user-images.githubusercontent.com/112809948/188313766-ecfd0c25-37b6-4470-8325-253b6f9517f4.png)

Please let me know if I can provide any further information :)

**Comment by thecodrr** [comment] 2022-09-04 12:43
Hey, thanks for reporting this issue. It looks like a duplicate of #869

**Closed** 2022-09-04 12:43 UTC
