### ISSUE TITLE
I would like to propose an important suggestion for justice. 🤝🏻

### ISSUE THREAD

**Issue by mnu9** [streetwriters/notesnook#3128] opened 2023-08-10 21:34 UTC
### What problem are you facing?

**I would like to add the Arabic language because it is the only language that does not exist**

### What's the solution you'd like to see in Notesnook?

Add Arabic only ♥️

**Comment by thecodrr** [comment] 2023-10-28 07:54
Closing as duplicate of #3493

**Closed by thecodrr** 2023-10-28 07:54 UTC
Labels: Type: Feature Request, Status: Pending
