### ISSUE TITLE
Date in Note title

### ISSUE THREAD

**Issue by sharemind** [streetwriters/notesnook#1279] opened 2022-11-03 10:10 UTC
### What problem are you facing?

When creating a new note for journaling I use the automatic creation of date in Note title.

**Note 11/3/22, 10:56 AM**

I would like to decide the prefered format of the date and time and the prefered text.

### What's the solution you'd like to see in Notesnook?

Create in the setting the option to decide what to write in the automatic title creation and which date and format to use.

YYYY/MM/DD
DD/MM/YYYY
DD/MM/YY
...
etc..

It will be usefule to have a text filed where you can write whatever you want and then be able to use some place holders within the text LIKE: [DATE-FORMAT] [TIME-FORMAT] [POSITION] [NOTEBOOK] [TOPIC]

**Comment by thecodrr** [comment] 2023-01-07 10:59
Marking as duplicate of #959

**Closed by thecodrr** 2023-01-07 10:59 UTC
Labels: Type: Feature Request, Status: Pending
