### ISSUE TITLE
Hourly and yearly Reminder

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#3233] opened 2023-08-30 08:19 UTC
### What problem are you facing?

Hourly and Yearly reminders are not available

### What's the solution you'd like to see in Notesnook?

Just like Daily, Weekly and Monthly reminders there should also be hourly and yearly/annual reminders.

**Comment by thecodrr** [comment] 2023-09-04 10:33
Duplicate of #1732

**Closed by thecodrr** 2023-09-04 10:33 UTC
Labels: Type: Feature Request, Status: Pending
