### ISSUE TITLE
Support line wrapping and line numbers in code block

### ISSUE THREAD

**Issue by ckdanny** [streetwriters/notesnook#3377] opened 2023-09-18 03:57 UTC
### What problem are you facing?

Supporting line wrapping and line numbers in code blocks would be incredibly helpful. Some code may be lengthy and occupy a single line, or there may be a long command. Additionally, displaying line numbers in code blocks can significantly assist in referencing a specific set of codes.

### What's the solution you'd like to see in Notesnook?

N/A. For line wrapping, manually break it into new line.

**Comment by thecodrr** [comment] 2023-10-30 05:34
Duplicate of #1748

**Closed by thecodrr** 2023-10-30 05:34 UTC
Labels: Type: Feature Request, Status: Pending
