### ISSUE TITLE
The app crashes when I attempt to maximize it

### ISSUE THREAD

**Issue by santirodriguez** [streetwriters/notesnook#3532] opened 2023-10-06 16:52 UTC
### What happened?

The application crashes when I attempt to maximize it.

### Steps to reproduce the problem

    Launch the application.
    Try to maximize the application window.
    The application consistently crashes.

Version: Ubuntu 23.04, Flatpak, Wayland.

### Version

2.6.7-0aac29c-desktop

### Platform/OS

Linux

### Relevant log output

```shell
Not relevant at all, but I wanted to say Hi, I'm in the process of transitioning away from Standard Notes due to their decision to no longer maintain an open-source model, and I've come across this alternative. Thanks!
```

**Comment by thecodrr** [comment] 2023-10-30 07:10
Duplicate of #3401

**Closed by thecodrr** 2023-10-30 07:10 UTC
Labels: Type: Bug, Status: Pending
