### ISSUE TITLE
Add support for using multiple browser windows side-by-side

### ISSUE THREAD

**Issue by koraa** [streetwriters/notesnook#1367] opened 2022-11-21 16:20 UTC
### What happened?

I was trying to edit a file side by side in two browser windows but edits from one document where discarded.

The best way to enable concurrent editing features would be to integrate a collaborative editor such as hedgedoc.

### Steps to reproduce the problem

--

### Version

--

### Platform/OS

Other browser

### Relevant log output

```shell
--
```

**Comment by thecodrr** [comment] 2022-11-21 17:28
> I was trying to edit a file side by side in two browser windows but edits from one document where discarded.

Yes, this is not currently possible (but will be when multi window support is added). The best solution to this is to use the second instance of Notesnook from an incognito window or a different browser. It'll work better that way.

**Comment by thecodrr** [comment] 2022-11-24 10:03
Marking this as duplicate of #688 as it doesn't add anything new.

**Closed by thecodrr** 2022-11-24 10:03 UTC
Labels: Type: Bug, Status: Pending
