### ISSUE TITLE
Custom app password or PIN

### ISSUE THREAD

**Issue by trymeouteh** [streetwriters/notesnook#1139] opened 2022-10-04 20:50 UTC
### What problem are you facing?

When I set the privacy of my client to be more strict, I am forced to use my account password which is long.

### What's the solution you'd like to see in Notesnook?

When the  privacy of my client is set to be more strict, to be able to use an client password or pin which is required to unlock the client.

### What alternatives have you considered?

Shorter account password but this will make my account password weaker.

**Comment by thecodrr** [comment] 2022-10-05 00:52
Duplicate of #319

**Closed by thecodrr** 2022-10-05 00:52 UTC
Labels: Type: Feature Request, Status: Pending
