### ISSUE TITLE
Notesnook how to operate can be realized within the notes quickly locate the specified position (anchor point jump function)

### ISSUE THREAD

**Issue by DavideSOGG** [streetwriters/notesnook#3112] opened 2023-08-08 17:06 UTC
I created the outline, though I didn't find a way to quickly jump around to locate it. markdown's [TOC] syntax doesn't seem to be supported. What can I do to enable positioning to a specific location within a note?

**Comment by thecodrr** [comment] 2023-08-09 00:59
This is not supported yet. Closing as duplicate of #2590

**Closed by thecodrr** 2023-08-09 00:59 UTC
