### ISSUE TITLE
Export to markdown: document files doesn't export as a external files

### ISSUE THREAD

**Issue by dmytrodubinin** [streetwriters/notesnook#3153] opened 2023-08-15 07:06 UTC
### What happened?

If I try to export my note with external files (such as images, pdf) it doesn't export as a files but only as a broken links (for example in pdf) and data:image for images

### Steps to reproduce the problem

After export my notes into markdown I got some problems
1. No external files exported
2. Images exported only as data:image inside files that very increase file size

For pdf files after export I got this.
In Notesnook:
![image](https://github.com/streetwriters/notesnook/assets/8066458/5b916e76-c919-4664-be16-bc3ace5593d0)
After export:
![image](https://github.com/streetwriters/notesnook/assets/8066458/d737e80a-2521-4b27-aec1-9f6b68a888cb)

For images.
In Notesnook:
![image](https://github.com/streetwriters/notesnook/assets/8066458/72dad6b0-6c68-4b70-a73e-ebae338ac757)
After export:
![image](https://github.com/streetwriters/notesnook/assets/8066458/57a61e27-6560-4a6c-ab26-8cc573d2ed2a)
In preview app such as MarkText:
![image](https://github.com/streetwriters/notesnook/assets/8066458/f89539de-da14-40c5-97fd-ab04c7461ff7)
Preview images works in some apps such as VSCode, but the files become very big and even VSCode can't open it. For example one of my note size increse from 100kb to 100Mb and VSCode break and files not readible!

Please fix export with external files (for example for pdf) and add option to export images as external files (not internal data:image)

### Version

2.6.1-e509c82-desktop

### Platform/OS

Linux

**Comment by thecodrr** [comment] 2023-10-28 08:09
Duplicate of #616

**Closed by thecodrr** 2023-10-28 08:09 UTC
Labels: Type: Bug, Status: Pending
