### ISSUE TITLE
Middle mouse button does not close tab when there are many tabs open

### ISSUE THREAD

**Issue by Leviob** [streetwriters/notesnook#4980] opened 2024-04-30 18:15 UTC
### What happened?

This is only an issue in Firefox with Autoscroll enabled: Once there are enough note tabs open that you must scroll to see all of them, middle clicking does not close the tab, but triggers Firefox's autoscroll feature (allowing you to scroll left and right through the tabs by dragging the mouse). 

Because there are time when I want to close many tabs quickly, but each tab is a different width, it takes a long time to click each "x". It is much more efficient to hover over the first tab, and middle click several times to close each tab. 

This interference with autoscrolling is present in both 3.0.0-583d585-web and 3.0.14-de226a8-web-beta

### Steps to reproduce the problem

1. Enable autoscrolling in Firefox settings. 
2. Open enough note tabs that you can scroll between them. 
3. Middle clicking on a tab does not close tab

### Version

3.0.14-de226a8-web-beta

### Platform/OS

Firefox

**Comment by aaronang** [comment] 2024-05-17 07:40
Isn't this a duplicate of #4979?

**Comment by Leviob** [comment] 2024-05-19 07:05
No. #4979 describes the middle mouse button not closing tabs _at all_ in the current version. Whereas, in 3.0.14-de226a8-web-beta, the middle mouse button _does_ close tabs. 

This issue describes an issue that is present in the current 3.0.6-10be577-web _as well_ as the 3.0.14-de226a8-web-beta version. This is an issue with horizontal scrolling preventing the middle mouse button from closing tabs in Firefox. Instead, middle clicking opens Firefox's autoscroll.

I added this issue because even if #4979 is fixed, the middle mouse button would still not work if enough tabs are open that you need to scroll to see all of them.  
Here's a What it looks like after trying to middle click to close a tab. Hopefully this adds context.

![Screenshot](https://github.com/streetwriters/notesnook/assets/59812528/31336fed-4416-4196-87f7-1ea89b7600c1)

I'm aware this issue might only affect a small subset of the users since autoscroll is a feature specific to Firefox.

**Closed** 2024-07-08 07:46 UTC
Labels: Type: Bug, Platform: Web, Platform: Desktop, Status: Confirmed, good first issue, Unit: UI/UX
