### ISSUE TITLE
Crash when maximize app

### ISSUE THREAD

**Issue by imhosseinzadeh** [streetwriters/notesnook#3556] opened 2023-10-11 16:51 UTC
### What happened?

[notesnook-crash.webm](https://github.com/streetwriters/notesnook/assets/89960731/dcca22ba-61c5-4f56-94f3-b5e0bb688024)

### Steps to reproduce the problem

I installed _notesnook_  2.6.4  by Flatpak and ran it.

### Version

2.6.4 

### Platform/OS

Linux

### Relevant log output

```shell
[3:1011/201054.777708:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1011/201055.008022:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1011/201055.008073:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
App ready. Opening window.
https protocol inteception "successful"
Intercepting request: https://app.notesnook.com/
Intercepting request: https://app.notesnook.com/assets/index-fe44bc43.js
Intercepting request: https://app.notesnook.com/assets/index-00536d7a4c5a.css
Intercepting request: https://app.notesnook.com/assets/nncrypto.worker-9e2f891e.js
Intercepting request: https://app.notesnook.com/assets/task-scheduler.worker-7f63a689.js
Intercepting request: https://app.notesnook.com/assets/index-d422b8543bdf.js
Intercepting request: https://app.notesnook.com/assets/total-notes-259be9f8f366.js
Intercepting request: https://app.notesnook.com/assets/string-ad4550406e96.js
Intercepting request: https://app.notesnook.com/assets/random-4b33b3b0ddaf.js
Intercepting request: https://app.notesnook.com/assets/toast-efb073b968c3.js
Intercepting request: https://app.notesnook.com/assets/index-10cc9a2f8123.js
Intercepting request: https://app.notesnook.com/assets/browser-a0291a37f3e5.js
Intercepting request: https://app.notesnook.com/assets/toast-dea4ca770e0f.css
Intercepting request: https://app.notesnook.com/assets/compressor-bb6588a58405.js
Intercepting request: https://app.notesnook.com/assets/network-check.worker-aed75908.js
Intercepting request: https://app.notesnook.com/assets/app-32eb08113506.js
Intercepting request: https://app.notesnook.com/assets/index-70b5b8f55bdd.js
Intercepting request: https://app.notesnook.com/assets/index-6e8284eb3eb3.js
Intercepting request: https://app.notesnook.com/assets/index-4816d68c780f.js
Intercepting request: https://app.notesnook.com/assets/body-f6a47e58e182.js
Intercepting request: https://app.notesnook.com/assets/index-0c07cdbefb90.css
Intercepting request: https://app.notesnook.com/assets/use-persistent-state-e9c993ce21a5.js
Intercepting request: https://app.notesnook.com/assets/index-248890c9864e.js
Intercepting request: https://app.notesnook.com/assets/app-effects-1a13f1b29492.js
Intercepting request: https://app.notesnook.com/assets/onboarding-dialog-1fb401044ed3.js
Intercepting request: https://app.notesnook.com/assets/nomad-3f2c5084a6dc.js
Intercepting request: https://app.notesnook.com/assets/index-1cc1afe20d11.js
Intercepting request: https://app.notesnook.com/assets/index-049d895a43e2.js
Intercepting request: https://app.notesnook.com/assets/index-31721d29cf61.js
Intercepting request: https://app.notesnook.com/assets/picker-765b4f5b7ed0.js
Intercepting request: https://app.notesnook.com/assets/index-610f0b3baab8.css
Intercepting request: https://app.notesnook.com/assets/open-sans-v34-vietnamese_latin-ext_latin_hebrew_greek-ext_greek_cyrillic-ext_cyrillic-regular-52a27a6a1c18.woff2
APPIMAGE env is not defined, current application is not an AppImage
Intercepting request: https://app.notesnook.com/assets/open-sans-v34-vietnamese_latin-ext_latin_hebrew_greek-ext_greek_cyrillic-ext_cyrillic-600-0240d31750de.woff2
Intercepting request: https://app.notesnook.com/assets/feature-dialog-677f77e74105.js
/app/bin/start-notesnook: line 2:     3 Segmentation fault      (core dumped) zypak-wrapper.sh /app/bin/notesnook --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations "$@"
```

**Comment by thecodrr** [comment] 2023-10-30 07:46
Duplicate of #3401

**Closed by thecodrr** 2023-10-30 07:46 UTC
Labels: Type: Bug, Status: Pending
