### ISSUE TITLE
Syncing is broken, erases your edits and reverts notes to prev versions. CRUCIAL

### ISSUE THREAD

**Issue by mockinbirdy** [streetwriters/notesnook#5615] opened 2024-05-12 19:40 UTC
### What happened?

Since there is a multitude of similar reports, all submitted via the "report an issue" button (and therefore not labeled as BUGs), it seems like one more opened issue with a big, red flair may help attract developers' attention to this critical matter.

My device information
App version: 3.0.3-web
OS: Windows 10
Browser: Firefox latest

My other device information
App version: 3.0.3-android

Story time: notesnook didn't sync my notes. Yesterday, after syncing my note from the web, I proceeded to edit it on Android several hours later. However, this morning when I opened my web and it synced, it did not reflect my latest changes (made on my Android device), instead showing an older version (saved from the web yesterday).

Not sure how to do my edits for now, since it's work related; _sighs_.

### Steps to reproduce the problem

1. edit a note, save it
2. open the note on another device, see how it doesn't sync properly and shows you the prev version instead 
3. (luckily the note history on the latest device it was edited on has the newest version and you can restore it)

### Version

3.0.3-4

### Platform/OS

Android, Firefox

### Relevant log output

```shell
no errors shown
```

**Comment by thecodrr** [comment] 2024-05-13 11:24
I am able to reproduce it like this:

1. Turn device A offline
2. Edit a note
3. Wait a bit
4. Edit the same note on Device B that is online
5. Turn device A online again
6. Wait for sync to complete on device A
7. Notice how the changes from device B are lost even though those changes were made later.

**Comment by thecodrr** [comment] 2024-05-15 10:54
This issue should be fixed in the upcoming release.

The bug was caused by the `dateModified` property on the item getting updated right after pushing the item to the server even if you edited that item hours ago (but didn't sync). In your case, something like this took place:

1. You made edits on the web app
2. Before sync could complete you closed the web app (or put the laptop/pc to sleep)
3. Several hours later, you made some edits on the Android app and also synced them
4. Next morning when you opened the web app again, it tried to finish its sync and pushed the unsynced but outdated content to the server and bumped the `dateModified` property too.
5. It also downloaded the changes made by the Android app but since the `dateModified` property of the note on the web app was more latest than the one on the server, it kept the web app copy instead of the Android one.

Of course, it is possible that the problem is completely different. However, the above is a scenario that I was able to continuously reproduce.

Another change I made to the sync system is that now you'll get a conflict in the above scenario (where you have some unsynced but older changes).

In any case, I'll leave this issue open until you are sure the problem is fixed.

**Comment by mockinbirdy** [comment] 2024-05-15 16:37
A little detail, I created #1note from scratch in my web browser (I had no #1note before, so I had no #1note on Android, so it must have synced from web nicely since I was able to edit it on my phone later).

**Comment by thecodrr** [comment] 2024-05-16 03:57
That changes things. So to be clear, something like this happened:

1. You created a note on your web app
2. The note synced to your Android device
3. You later edited it on your Android device
4. In the morning when you opened the web app, the sync completed but it did not download the changes you made on the Android device. In fact, it also replaced the note on the Android device with an older version.

Is that correct?

In that case, the above can be explained as follows:

In the morning when you opened the web browser, either you made an accidental edit or the app incorrectly saved the note again BEFORE the first sync could run. That would explain why that note got sent to the Android device even though it was an older version. You can check if this is the case by viewing the note history on the web browser: there should be an entry at the time you first opened the web browser in the morning.

Another case is that you made an accidental change the previous day, right before you closed the web browser, and it couldn't sync. When you opened the browser in the morning, it tried to sync that change.

The reason I keep insisting on a change having been made is because the sync can never send an item that wasn't edited/changed. It only uploads something if it is changed either by the user or the app itself. Otherwise, it is continously ignored.

**Comment by mockinbirdy** [comment] 2024-05-19 23:41
Yes, correct. I'll try to see, if it will happen again after the update.

**Comment by thecodrr** [comment] 2024-06-05 07:11
@mockinbirdy are you still experiencing this issue?

**Comment by thecodrr** [comment] 2024-07-01 07:07
Closing this issue. Feel free to reopen if you face the same problem again.

**Closed by thecodrr** 2024-07-01 07:07 UTC
Labels: Type: Bug, Status: Pending
