### ISSUE TITLE
Date in Note title

### ISSUE THREAD

**Issue by sharemind** [streetwriters/notesnook#1278] opened 2022-11-03 09:59 UTC
### What happened?

The Mac OS app create the automatic Note tile as follow:

Note 11/3/22, 10:56 AM

while the Android and Web App as follow:

Note 03/11/22, 10:57

It should have the same date and time format

### Steps to reproduce the problem

Create a new note.

### Version

Versione 2.2.3 (222)

### Platform/OS

macOS

**Comment by Romancha** [comment] 2022-11-12 17:28
Same issue

**Comment by thecodrr** [comment] 2023-01-07 10:59
Marking as duplicate of #959

**Closed by thecodrr** 2023-01-07 10:59 UTC
Labels: Type: Bug, Status: Pending
