### ISSUE TITLE
Drag and drop bullets

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#3304] opened 2023-09-11 01:29 UTC
### What's the solution you'd like to see in Notesnook?

 I would like ability to drag and drop bullets or have the ability to move them with the mobile keyboard.

**Comment by luxcalor** [comment] 2023-09-15 11:57
Yes to this for sure.

**Comment by thecodrr** [comment] 2023-10-28 11:06
Duplicate of #2726

**Closed by thecodrr** 2023-10-28 11:06 UTC
Labels: Type: Feature Request, Status: Pending
