### ISSUE TITLE
Drawing/Writing/Image Editor

### ISSUE THREAD

**Issue by trymeouteh** [streetwriters/notesnook#1136] opened 2022-10-04 19:41 UTC
### What problem are you facing?

Being able to draw, write with a stylus and have a basic image editor to edit JPG and PNG files.

### What's the solution you'd like to see in Notesnook?

Being able to draw, write with a stylus and have a basic image editor to edit JPG and PNG files.

To have text notes and image notes.

**Comment by thecodrr** [comment] 2023-07-29 01:33
Duplicate of #996 and #895

**Closed by thecodrr** 2023-07-29 01:33 UTC
Labels: Type: Feature Request, Status: Pending
