### ISSUE TITLE
Scrolling lag on desktop app (Ubuntu and Windows 10)

### ISSUE THREAD

**Issue by dtantono** [streetwriters/notesnook#725] opened 2022-07-24 02:52 UTC
### What happened?

when searching notes, there is a scrolling lag on desktop app (Ubuntu and Windows 10). But, this problem does not exist in web app. 

### Steps to reproduce the problem

1. open the app
2. click the top left icon (notes)
3. click the desirable note
4. Scroll the notes
5. The problem appears

### Version

2.1.2

### Platform/OS

Windows, Linux

**Comment by thecodrr** [comment] 2022-07-25 10:36
Hey, can you send a video? I can't reproduce this.

**Comment by dtantono** [comment] 2022-07-25 11:15
This is for Linux client and I blurred this video because there is my confidential information within. 
[2022-07-25 20-09-17.mkv.zip](https://github.com/streetwriters/notesnook/files/9180594/2022-07-25.20-09-17.mkv.zip)

**Comment by thecodrr** [comment] 2022-07-25 11:23
From the blurred list I cannot notice an issue. The scroll speed seems normal to me.

**Comment by dtantono** [comment] 2022-07-25 13:19
the scrolling speed is not really fluid unlike I browse normally in the browser

**Comment by thecodrr** [comment] 2022-07-25 14:54
Are you talking about smooth scroll?

**Comment by dtantono** [comment] 2022-07-26 00:17
yes

**Comment by thecodrr** [comment] 2022-09-08 12:25
@jon-rei how many items do you have in the list?

**Comment by jon-rei** [comment] 2022-09-08 12:30
Overall I have 165 notes but this also happens in Notebook topics which only have around 35 notes. In both cases the scrolling is breaking.

**Comment by thecodrr** [comment] 2022-09-08 12:36
@jon-rei can you send a short video?

**Comment by jon-rei** [comment] 2022-09-08 13:02
https://user-images.githubusercontent.com/21036205/189128264-ff2fee40-9e87-40ae-a680-67beecb4d09e.mov

While I was recording the video I was constantly scrolling with my mouse wheel and only when I had some small breaks between the scrolling it would let me scroll again.
Moreover at some point the Scrollbar turned white (maybe another issue).

**Comment by thecodrr** [comment] 2023-03-27 17:58
Closing this as I haven't been able to reproduce this on any device/platform. Feel free to comment if you are still facing this issue in v2.4.6.

**Closed by thecodrr** 2023-03-27 17:58 UTC
Labels: Type: Bug, Status: Pending
