### ISSUE TITLE
Want to develop the ability to share edit notes

### ISSUE THREAD

**Issue by f0restw0w** [streetwriters/notesnook#3080] opened 2023-08-04 06:29 UTC
### What problem are you facing?

Want to develop the ability to share edit notes

### What's the solution you'd like to see in Notesnook?

Want to develop the ability to share edit notes

**Comment by thecodrr** [comment] 2023-08-04 14:37
Duplicate of #20

**Closed** 2023-08-04 14:37 UTC
Labels: Type: Feature Request, Status: Pending
