### ISSUE TITLE
Flatpak version doesn't follow the custom cursor theme

### ISSUE THREAD

**Issue by dmytrodubinin** [streetwriters/notesnook#3152] opened 2023-08-15 06:35 UTC
### What happened?

Flatpak version of Notesnook doesn't follow the custom cursor theme on Linux.

### Steps to reproduce the problem

Here is the demo with Flatpak version on the left and AppImage version on the right. As you can see AppImage version follow custom cursor theme but Flatpak not 

https://github.com/streetwriters/notesnook/assets/8066458/b99d4428-c256-42c7-b84e-316e59c479a5

### Version

2.6.1-e509c82-desktop

### Platform/OS

Linux

**Comment by thecodrr** [comment] 2023-10-28 08:07
This is duplicate of #2787

**Closed** 2023-10-28 08:08 UTC
Labels: Type: Bug, Status: Pending
