### ISSUE TITLE
"sale of the year" not loading

### ISSUE THREAD

**Issue by ghost** [streetwriters/notesnook#3861] opened 2023-11-24 10:17 UTC
### What happened?

![image](https://github.com/streetwriters/notesnook/assets/138553763/777f1405-487f-488c-a7a9-359e7c02eab1)

### Steps to reproduce the problem

click on subscribe button on "sale of the year" notification

### Version

2.6.11

### Platform/OS

Linux

### Relevant log output

*No response*

**Comment by thecodrr** [comment] 2023-11-24 10:53
Hi, please try from the web app. There's a bug that is preventing users from purchasing from the desktop app.

Closing as duplicate of #3860

**Closed as completed by thecodrr** 2023-11-24 10:53 UTC
Labels: Type: Bug, Status: Pending
