### ISSUE TITLE
Paste URL onto selected text to hyperlink it

### ISSUE THREAD

**Issue by JVimes** [streetwriters/notesnook#3570] opened 2023-10-15 01:51 UTC
### What problem are you facing?

There's a really easy way to do hyperlinks in Slack, but Notesnook doesn't have it yet

### What's the solution you'd like to see in Notesnook?

To hyperlink text:

1. Place URL on clipboard
2. Select text in Notesnook
3. Paste

**Comment by thecodrr** [comment] 2023-10-30 07:59
Duplicate of #3520

**Closed by thecodrr** 2023-10-30 07:59 UTC
Labels: Type: Feature Request, Status: Pending
