### ISSUE TITLE
[Feature Request] Support 1 search box to search across different type

### ISSUE THREAD

**Issue by ckdanny** [streetwriters/notesnook#3748] opened 2023-11-11 14:45 UTC
### What problem are you facing?

Currently, it is not possible to search across different types, as each type has its own search bar.

There is also no search short-cut in which users need to click on the icon to search each time. 

### What's the solution you'd like to see in Notesnook?

I believe that it would be much more convenient to have a single search box that allows users to search for multiple types of items. To make this even easier, I suggest adding `Command+Shift+F` as a shortcut to trigger the search, and allowing users to search for tags (using the `#` prefix) and full text searches.

### What alternatives have you considered?

N/A

**Comment by thecodrr** [comment] 2023-11-13 04:16
Duplicate of #145

**Closed by thecodrr** 2023-11-13 04:16 UTC
Labels: Type: Feature Request, Status: Pending
