### ISSUE TITLE
Text selection is tricky [Android]

### ISSUE THREAD

**Issue by luxcalor** [streetwriters/notesnook#2510] opened 2023-05-08 19:04 UTC
### What happened?

https://user-images.githubusercontent.com/76074147/236908112-5faf1816-de58-4deb-b466-9f1be1972533.mp4

It is very tricky to extend selection area after selecting one or several words. Might be a tap area issue. The selection also disappears too easily while scrolling. I suppose this was not the case in previous versions, as the selection process seemed to be solid on Android. 

I have recently updated my phone to Android 13 so that might be an issue. 

### Steps to reproduce the problem

Select a word by long tap or several words by long tap and drag -> try to extend the selection by tapping and dragging the mark 

### Version

2.4.15

### Platform/OS

Android

**Comment by luxcalor** [comment] 2023-05-09 11:14
UPD: this most probably is an effect of Android 13 update. But only a few apps on my phone are affected, NN being one of them. In others, like Google Keep, Docs, Evernote selecting text works fine or even smoother than before.

**Comment by thecodrr** [comment] 2023-05-15 08:16
@luxcalor I tried to reproduce this on Android 13 but couldn't. I have an LG device. What keyboard are you using? Maybe that has something to do with this. Can you try a different keyboard?

**Comment by luxcalor** [comment] 2023-05-15 11:39
@thecodrr did check with GBoard (which is stock on my phone) and OpenBoard. The behaviour is absolutely the same. This happens on Xiaomi phone MIUI 14, Android 13. Did check on Android 10 MIUI 12 running phone and everything works fine as it used to before on my phone. 

As mentioned before, this selection problem happens on handful of apps after a recent update to A13. But most of the apps are fine, or arguably even better. Text selection in Google keep, for example, became noticebly smoother.

**Comment by thecodrr** [comment] 2023-09-14 11:37
Closing since I cannot reproduce this on any device.

**Closed** 2023-09-14 11:37 UTC
Labels: Type: Bug, Status: Pending

**Comment by thecodrr** [comment] 2023-09-14 13:26
@luxcalor still can't reproduce this even when the selection popup appears above the cursor.

**Comment by luxcalor** [comment] 2023-09-14 13:28
> @luxcalor still can't reproduce this even when the selection popup appears above the cursor.

It happens when popup is below the cursor, not above.

**Comment by thecodrr** [comment] 2023-09-14 13:29
Below or above makes no difference on my end.

**Comment by luxcalor** [comment] 2023-09-14 13:38
https://github.com/streetwriters/notesnook/assets/76074147/e237ef32-c856-4807-a993-3ce38055a3ac

**Comment by luxcalor** [comment] 2023-09-16 09:27
> @thecodrr This still happens when the editing popup appears below the cursor. Selection becomes tricky to impossible. If the popup appears above the cursor it is working mostly fine.

Checked this on another phone (Android 10) and under different account. There is the same problem.
