### ISSUE TITLE
End-of-2022 desiderata: spell check for PC app and Android, and PC app auto-lock

### ISSUE THREAD

**Issue by umbellipher** [streetwriters/notesnook#1519] opened 2022-12-21 15:25 UTC
### What problem are you facing?

See the next box.

### What's the solution you'd like to see in Notesnook?

My end-of-2022 desiderata to make Notesnook a much better experience:

1) PC app and Android: re-enable spell checking. It is such a pain not to have it.

2) PC app: auto-lock option after a chosen number of seconds. If this can be done on Android, why not on the PC app?

**Comment by thecodrr** [comment] 2023-01-07 09:33
Duplicate of #404 & #1140

**Closed by thecodrr** 2023-01-07 09:33 UTC
Labels: Type: Feature Request, Status: Pending
