### ISSUE TITLE
Better keyboard shortcuts

### ISSUE THREAD

**Issue by justin13888** [streetwriters/notesnook#6340] opened 2024-08-12 15:40 UTC
### What problem are you facing?

Notesnook on desktop is incredibly fast and lightweight for an Electron app. It would be great if there could be a well-developed list of keyboard shortcuts (e.g. creating new page with Ctrl+N; switching to next tab with Ctrl+Tab)

### What's the solution you'd like to see in Notesnook?

1. Provide reasonable keyboard shortcuts for common tasks
2. Make keyboard shortcuts user-configurable

### What alternatives have you considered?

N/A

### Additional context

Some potentially helpful resources:

* Notion has some keyboard shortcuts that could be referenced when building out these keyboard interactions: https://www.notion.so/help/keyboard-shortcuts
* VS Code also does an amazing job to make keyboard shortcuts highly customizable: https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization

```[tasklist]
### Tasks
```

**Comment by PJUllrich** [comment] 2024-09-13 08:33
+1 for this. I'd be great to have a shortcut for the focus mode too. That way, I could quickly create a new note (CMD+N on macOS), toggle the focus mode (CMD+Something), and start writing.

**Comment by thecodrr** [comment] 2024-10-15 07:36
Duplicate of #105

**Closed** 2024-10-15 07:37 UTC
Labels: Type: Feature Request, Status: Pending

**Comment by blijonline** [comment] 2024-10-15 16:50
Agree and strange that there are no keyboard shortcuts already! 

I also like the approach which Obsidian uses with their command pallet. Shortcuts will be a great time saver and will give the use experience a nice boost!

Hope you will implement them soon.

**Comment by gurubyte** [comment] 2024-11-23 23:35
Also being able to edit shortcuts would be sooo useful
