### ISSUE TITLE
Share files with the app in Android (and audio recorder)

### ISSUE THREAD

**Issue by jrcacd** [streetwriters/notesnook#535] opened 2022-04-19 16:48 UTC
Sound files (wave, mp3, AAC (audio notes from other files) PDFs and images.
An alternative could be to have his own audio recorder (with pause option) to record notes inside notesnook (because it's a way faster to speak the notes comparing to type them, on cell phone or tablet)

**Comment by thecodrr** [comment] 2022-07-18 02:33
Duplicate of #217

**Closed by thecodrr** 2022-07-18 02:33 UTC
